# Site settings
title: Data Science Africa
location: Addis Ababa, Ethiopia (3rd - 7th June 2019)
city: Addis Ababa
year: 2019
email: info@datascienceafrica.org
banner: AddisAbabaUniversity.jpg
description: > # this means to ignore newlines until "baseurl:"
  The 2019 Data Science Africa summer school held at Addis Ababa University.
baseurl: "/dsa2019addis" # the subpath of your site, e.g. /blog/
url: "http://www.datascienceafrica.org" # the base hostname & protocol for your site
twitter_username: datascienceafrica.org #DatSciAfrica
logo_url: img/logo.png
github_username:  datsciafrica

other:
  url: /dsa2019accra/
  text: |
    <div class="" style="
                        font-weight: bold; 
                        font-size: 18px;

                        ">Next: Data Science Africa 2019</div>
    <div> Dates: October 21<sup>st</sup> - October 25<sup>th</sup></div>
    <div>Accra, Ghana</div>

previous:
  url: /dsa2018abuja/
  text: | # From here to "school:"
    <div class="" style="
                        font-weight: bold; 
                        font-size: 18px;

                        ">Previous: Data Science Africa 2018 </div>
    <div>November 12<sup>th</sup>  - November 17<sup>th</sup> 2018</div>
    <div>Abuja, Nigeria</div>

social:
  title: Social Event
  text:
  
school:  
  name: Data Science in Africa School
  shortname: DSA2019
  location: "Addis Ababa University, Addis Ababa"
  googleformid: 
  dates:		
  - 2019-06-03
  - 2019-06-04
  - 2019-06-05
  registration:
    deadline: 2019-05-10
    open: False
  draft: Y # set to Y if the programme is draft only.
  roles:
  - {type: Organizer, name: Michael Melese, url: "https://sites.google.com/site/cwamainadekut"}  
  - {type: Organizer, name: Dina Machuve, url: "http://air.ug/~mmubangizi"}
#  - {type: Organizer, name: Charles I. Saidu, url: "http://air.ug/~jquinn"}
#  - {type: Organizer, name: Samuel Grace Kehinde, url: "http://air.ug/~jquinn"}

conference:
  shortname: DSA2019Addis
  theme: 
  hosts:
  roles:
  - {type: General Chair, name: Michael Melese, url: "", email: "michael.melese@aau.edu.et"}
  - {type: Program Chair, name: Dina Machuve, url: "http://twiga2.github.io/dmachuve", email: "dmachuve@gmail.com"}
  name: Data Science in Africa Workshop 
  location: "Addis Ababa University, Ethiopia"
  googleformid: LVzZqd2Ci1YVeJZa9
  year: 2019
  month: June
  registration:
    deadline: 2019-05-03
    open: False
  # add other days here for them to appear
    abstract: 
      deadline: 2019-05-03
      googleformid: xeCESJonBotRve5u9
  dates:	
  - 2019-06-06
  - 2019-06-07
  draft: Y # set to Y if the programme is draft only.
  organizers:
  - {logo: sheffield.png, name: University of Sheffield}
  - {logo: makerere.png, name: Makerere University}
  - {logo: plklogo.png, name: Pulse Lab Kampala}
  - {logo: dedan_kimathi.png, name: Dedan Kimathi University of Technology}
  - {logo: nmaist-logo.png, name: Nelson Mandela African Institute of Science and Technology}
  - {logo: aust.jpg, name: African University of Science and Technology, Abuja}
  - {logo: Addis_Ababa_University_logo.png, name: Addis Ababa University}
  - {logo: Google.png, name: Google AI, Ghana}
  - {logo: parisuni.png, name: Univ Paris, France}
  - {logo: zindi.png, name: Zindi, South Africa}
  goldsponsors: 
  #- {logo: facebook.png, name: "Facebook"}  
  #- {logo: google.png, name: "Google"}
  - {logo: arm-logo-blue-rgb.png, name: "ARM", url: "https://www.arm.com/"}
  #- {logo: ArmMbedLogo.png, name: "ARM mbed", url: "https://www.mbed.com/en/"}
  #- {logo: Amazon-logo-RGB.png, name: "Amazon", url: "https://www.amazon.com/"}
  silversponsors:
  #- {logo: deepmind_logo.png, name: "DeepMind", url: "https://deepmind.com/"}
  #- {logo: Google.png, name: "Google", url: "https://www.google.com/"}
  - {logo: Voyage.png, name: "Voyage", url: "https://www.voyage.auto/"}
  bronzesponsors:
  - {logo: ApexAI.webp, name: ApexAI,url: "https://www.apex.ai/"}
  - {logo: gigster.png, name: Gigster,url: "https://www.gigster.com/"}
  - {logo: max.jpg, name: Max, url: "https://staff.fnwi.uva.nl/m.welling/"}

feedback: 




exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

sass:
    sass_dir: _scss

# Build settings
markdown: kramdown


analytics:
  google:
    tracking_id: UA-80484960-1

video:
  height: 315
  width: 560

future: true
